feat: 커플 디데이 기능 추가-BE
bit-o-gi/project pull request #12
Opened 2024-08-15 13:23 UTC by jmeancode

2024-08-16 03:38 UTC, ParkSeryu requested changes

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/dto/CoupleDdayDto.java
> +    private String partner2;
p2; partner1 partner2과같은 네이밍은 지양하는게 좋아보입니다.

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/dto/CoupleDdayDto.java
> +    // Getters and Setters
p3; 롬복어노테이션 대신에 메소드를 구현한 이유가 있을까요?

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/entity/CoupleDday.java
> +@Setter
p1; Entity에서는 특히, Setter는 지양하는게 나아보여요

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/entity/CoupleDday.java
> +@AllArgsConstructor
p2; 해당 클래스에 이 많은 어노테이션들이 들어갈 이유가 궁금합니다

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/entity/CoupleDday.java
> +    @Column
p2; @Column을 사용한 이유가 있을까요??

1. 매핑의 이유
2. 제약조건을 적용하기 위해
두개 다 아닌것 같아보여서 물어봅니당

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/service/impl/CoupleDdayServiceImpl.java
> +        coupleDday.setDdayDate(dto.getDdayDate());
p1; entity에 직접 set을 하면, CoupleDday 객체가 안전한 객체라는 신뢰도 깨질 수 있고,
후에 발생할 버그등에 대해서도 추적하기가 어려워 지는 등의 우려가 있어요.
entity에 builder 어노테이션이 달려있었는데, 해당 패턴 사용해서 값을 넣어주는 것으로 바꿔보는게 어떨까요?

2024-08-16 03:38 UTC, ParkSeryu commented on src/main/java/bit/dday/service/impl/CoupleDdayServiceImpl.java
> +        responseDto.setDdayDate(savedCoupleDday.getDdayDate());
p2; 이런 방식으로 구현을 하다 보면,
필연적으로 서비스 레이어가 신이 될 수 밖에 없어요.
조금 더 객체지향적으로 구현해 보는게 어떨까요?

2024-08-16 03:38 UTC, ParkSeryu commented on src/test/java/bit/dday/service/CoupleDdayServiceImplTest.java
> +        assertEquals(dto.getDdayDate(), result.getDdayDate());
p1; 이렇게 비교를 하는거면, when단은 없어도 될 것 같은 느낌이 드는데..
테스트 주체에 대한 검증이 제대로 이루어 지지 않고 있는것같아요~

2024-08-16 03:38 UTC, ParkSeryu commented
test

2024-08-16 03:39 UTC, ParkSeryu requested changes
test

2024-08-16 03:45 UTC, ParkSeryu commented on src/main/java/bit/dday/controller/CoupleDdayController.java
> +package bit.dday.controller;
pr 커밋 하나에 다 이루어져 있는건
형상 관리적 측면에서도,
리뷰어 입장에서 지민님의 개발 흐름과 생각에 대한 측면을 엿볼수 없다는게 
아쉽습니다,

사람마다 기준은 다 다르지만
조금 더 단위기능으로 커밋을 쪼개서 작업하는게 어떨까 싶네요~

2024-08-16 07:41 UTC, bong94688 reviewed
좋은코드 잘봤습니다. 감사합니다.

2024-08-16 07:41 UTC, bong94688 commented on src/main/java/bit/dday/dto/CoupleDdayDto.java
> +    public void setPartner1(String partner1) {
캡슐화를 시켜주는건 어떤가요?

2024-08-23 09:04 UTC, ParkSeryu commented on src/main/java/bit/dday/dto/CoupleDdayDto.java
> +    private String partner2;
변수명은 러프하게 잡아도 작성자의 최소한의 의도는 담겨야 한다고 생각해요
위와 같은 경우엔 `Sender / Receiver` 라던지,
`FromUserNm / ToUserNm` 정도만이라도 되어있으면
모르는 사람이 봐도 어느정도 의도를 파악할 수 있지 않을까요?

2024-08-23 09:36 UTC, jmeancode commented on src/main/java/bit/dday/dto/CoupleDdayDto.java
> +    // Getters and Setters
특별한 이유는 없었습니다!

2024-08-23 09:36 UTC, jmeancode commented on src/main/java/bit/dday/entity/CoupleDday.java
> +@Setter
지양하겠습니다.

2024-08-25 09:39 UTC, closed without merging